feat: add support for volume mounts
k6io/operator pull request #13
Opened 2021-05-11 11:52 UTC by victorlcm

Hi everyone,

I'm currently trying to use the k6 operator to implement a load testing solution in the company I work. We have some pretty aggressive scenarios with some big files to be loaded in the init phase to be used by all VUs. Due to these big files, I got an error when trying to create the scripts as config maps, because they cannot exceed 3mb in size. So, to solve this I've modified the operator a little bit to also accept a persistent volume claim. With the claim, it will not mount volume using config maps, but will mount using the claim name. With this, we can add the code anywhere it's supported by Kubernetes and we'll not have issues with file sizes. I've also increased the manager requests/limits a little bit as the pod was getting a lot of OOMKill from the cluster.

Please let me know whether I can improve anything and I'll do it asap!

2021-05-11 13:14 UTC, victorlcm commented
Hey @simskij 

Thanks! Sure, I'll try my best to contribute with both suggestions, ideas and also some code! hahaha
This tool is so good and is helping a lot! distributing is always hard and this operator made it so much better

2021-06-07 13:29 UTC, victorlcm commented
hey @simskij,

I've just resolved the conflicts in this PR, did you have the chance to test it?

2021-06-11 07:15 UTC, simskij requested changes
LGTM! Some minor suggestions

2021-06-11 07:15 UTC, simskij commented on config/manager/manager.yaml
> +            memory: 60Mi
Let's bump this some more. As it's the burst limit, it doesn't really make sense to keep it too low, as you pointed out.
```suggestion
            memory: 100Mi
```

2021-06-11 07:15 UTC, simskij commented on pkg/resources/jobs/runner.go
> +					Volumes:                       newVolumeSpec(k.Spec.Script, k.Spec.VolumeClaim),
Maybe it would be preferable to pass the whole Spec instead of adding an additional param?

2021-06-11 07:15 UTC, simskij commented on api/v1alpha1/k6_types.go
> +	VolumeClaim string                 `json:"volumeClaim,omitempty"`
See line 24. If it's now possible to pick between using a volume and a config map, the script prop should be made optional as well.

2021-06-11 07:17 UTC, simskij commented
Over time, I think it would be desirable to make the usage like this (but I'm definitely not expecting you to do that change as part of this PR, just want to give you an idea of where I think we should be heading 😅 ):

```yaml
spec:
  script:
    volumeClaim:
      name: k6-test-files
      file: /a.test.bundle.js
    # or...
    configMap:
      name: k6-test-files-configmap
      file: test.js
```

2021-06-14 15:03 UTC, victorlcm commented
> Over time, I think it would be desirable to make the CRD look like this (but I'm definitely not expecting you to do that change as part of this PR, just want to give you an idea of where I think we should be heading 😅 ):
> 
> ```yaml
> spec:
>   script:
>     volumeClaim:
>       name: k6-test-files
>       file: /a.test.bundle.js
>     # or...
>     configMap:
>       name: k6-test-files-configmap
>       file: test.js
> ```

Hey @simskij 👋 

I really liked this change so I've already implemented and pushed into this PR. Could you please review it again? I'm new to Golang, so any inputs are appreciated 😄

2021-06-15 14:41 UTC, simskij requested changes
Two more minor changes, then we're good to go! 🎉

2021-06-15 14:41 UTC, simskij commented on pkg/resources/jobs/runner.go
> +}
```suggestion
func newScript(spec v1alpha1.K6Spec) (*Script, error) {
      s := &Script{}
      s.File = "test.js"
        
	if spec.Script.VolumeClaim.Name != "" {
		s.Name = spec.Script.VolumeClaim.Name		
		if spec.Script.VolumeClaim.File != "" {
			s.File = spec.Script.VolumeClaim.File
		}

		s.Type = "VolumeClaim"
		return s, nil
	}

	if spec.Script.ConfigMap.Name != "" {
		s.Name = spec.Script.ConfigMap.Name

		if spec.Script.ConfigMap.File != "" {
			s.File = spec.Script.ConfigMap.File
		}

		s.Type = "ConfigMap"
		return s, nil
	}

	return nil, errors.New("ConfigMap or VolumeClaim not provided in script definition")
}
```

2021-06-15 14:41 UTC, simskij commented on pkg/resources/jobs/runner.go
> +		"/test/"+script.File,
```suggestion
		fmt.Sprintf("/test/%s", script.File),
```

2021-06-15 14:54 UTC, victorlcm commented
thx for the comments!

2021-06-16 11:07 UTC, merged

2021-06-16 11:07 UTC, simskij commented
Thanks for the contribution! 🎉